# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/openBMP/amplicon.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_amplicon(object):
    def setupUi(self, amplicon):
        amplicon.setObjectName("amplicon")
        amplicon.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(amplicon)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(260, 70, 80, 15))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 60, 61, 31))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(140, 70, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 110, 61, 31))
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(140, 110, 113, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(270, 110, 80, 15))
        self.pushButton_2.setObjectName("pushButton_2")
        amplicon.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(amplicon)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 17))
        self.menubar.setObjectName("menubar")
        amplicon.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(amplicon)
        self.statusbar.setObjectName("statusbar")
        amplicon.setStatusBar(self.statusbar)

        self.retranslateUi(amplicon)
        QtCore.QMetaObject.connectSlotsByName(amplicon)

    def retranslateUi(self, amplicon):
        _translate = QtCore.QCoreApplication.translate
        amplicon.setWindowTitle(_translate("amplicon", "MainWindow"))
        self.pushButton.setText(_translate("amplicon", "Open metadata"))
        self.label.setText(_translate("amplicon", "Metadata path"))
        self.label_2.setText(_translate("amplicon", "Raw data"))
        self.pushButton_2.setText(_translate("amplicon", "Open fastq dir."))
