# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/openBMP/Matplotlib.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Matplotlib(object):
    def setupUi(self, Matplotlib):
        Matplotlib.setObjectName("Matplotlib")
        Matplotlib.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(Matplotlib)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(320, 120, 80, 15))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(140, 130, 41, 9))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(190, 120, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        Matplotlib.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Matplotlib)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 17))
        self.menubar.setObjectName("menubar")
        Matplotlib.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Matplotlib)
        self.statusbar.setObjectName("statusbar")
        Matplotlib.setStatusBar(self.statusbar)

        self.retranslateUi(Matplotlib)
        QtCore.QMetaObject.connectSlotsByName(Matplotlib)

    def retranslateUi(self, Matplotlib):
        _translate = QtCore.QCoreApplication.translate
        Matplotlib.setWindowTitle(_translate("Matplotlib", "MainWindow"))
        self.pushButton.setText(_translate("Matplotlib", "PushButton"))
        self.label.setText(_translate("Matplotlib", "TextLabel"))
