# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/openBMP/OpenBMP.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OpenBMP(object):
    def setupUi(self, OpenBMP):
        OpenBMP.setObjectName("OpenBMP")
        self.centralWidget = QtWidgets.QWidget(OpenBMP)
        self.centralWidget.setObjectName("centralWidget")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(10, 0, 371, 261))
        self.label.setObjectName("label")
        OpenBMP.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(OpenBMP)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 495, 17))
        self.menuBar.setObjectName("menuBar")
        self.menuBlast = QtWidgets.QMenu(self.menuBar)
        self.menuBlast.setObjectName("menuBlast")
        self.menuGO = QtWidgets.QMenu(self.menuBar)
        self.menuGO.setObjectName("menuGO")
        self.menuKEGG = QtWidgets.QMenu(self.menuBar)
        self.menuKEGG.setObjectName("menuKEGG")
        self.menuCOG = QtWidgets.QMenu(self.menuBar)
        self.menuCOG.setObjectName("menuCOG")
        self.menuOthers = QtWidgets.QMenu(self.menuBar)
        self.menuOthers.setObjectName("menuOthers")
        self.menuGames = QtWidgets.QMenu(self.menuBar)
        self.menuGames.setObjectName("menuGames")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        OpenBMP.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(OpenBMP)
        self.mainToolBar.setObjectName("mainToolBar")
        OpenBMP.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(OpenBMP)
        self.statusBar.setObjectName("statusBar")
        OpenBMP.setStatusBar(self.statusBar)
        self.actionAboout = QtWidgets.QAction(OpenBMP)
        self.actionAboout.setObjectName("actionAboout")
        self.actionUpdate = QtWidgets.QAction(OpenBMP)
        self.actionUpdate.setObjectName("actionUpdate")
        self.actionLocal_Blast_GUI = QtWidgets.QAction(OpenBMP)
        self.actionLocal_Blast_GUI.setObjectName("actionLocal_Blast_GUI")
        self.menuBlast.addAction(self.actionLocal_Blast_GUI)
        self.menuHelp.addAction(self.actionAboout)
        self.menuHelp.addAction(self.actionUpdate)
        self.menuBar.addAction(self.menuBlast.menuAction())
        self.menuBar.addAction(self.menuGO.menuAction())
        self.menuBar.addAction(self.menuKEGG.menuAction())
        self.menuBar.addAction(self.menuCOG.menuAction())
        self.menuBar.addAction(self.menuOthers.menuAction())
        self.menuBar.addAction(self.menuGames.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(OpenBMP)
        QtCore.QMetaObject.connectSlotsByName(OpenBMP)

    def retranslateUi(self, OpenBMP):
        _translate = QtCore.QCoreApplication.translate
        OpenBMP.setWindowTitle(_translate("OpenBMP", "OpenBMP"))
        self.label.setText(_translate("OpenBMP", "毛泽东"))
        self.menuBlast.setTitle(_translate("OpenBMP", "Blast"))
        self.menuGO.setTitle(_translate("OpenBMP", "GO"))
        self.menuKEGG.setTitle(_translate("OpenBMP", "KEGG"))
        self.menuCOG.setTitle(_translate("OpenBMP", "COG"))
        self.menuOthers.setTitle(_translate("OpenBMP", "Others"))
        self.menuGames.setTitle(_translate("OpenBMP", "Games"))
        self.menuHelp.setTitle(_translate("OpenBMP", "Help"))
        self.actionAboout.setText(_translate("OpenBMP", "Aboout"))
        self.actionUpdate.setText(_translate("OpenBMP", "Update"))
        self.actionLocal_Blast_GUI.setText(_translate("OpenBMP", "Local Blast GUI"))
